apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nielseniq-dev
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0a38dc5d877d76809 }
      us-east-1b: { id: subnet-05118e1cb7867ee9c }
      us-east-1c: { id: subnet-03a2a7d599264e259 }

nodeGroups:
  - name: nielseniq-dev-1-workers
    labels: { role: workers }
    instanceType: t3.xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true